package sso

import (
	"context"
	"encoding/json"
	"fmt"
)

// Identity is the provider-agnostic result of a successful SSO login.
//
// ─────────────────────────────────────────────────────────────────────────────
// (Provider, Subject) IS THE IDENTITY. EMAIL IS NOT, AND NEVER BECOMES IT.
//
// Subject is the IdP's stable, never-reassigned identifier for a human — `sub`
// in OIDC, which Core §2 requires to be locally unique and never reassigned.
// Paired with Provider it is the only correct key for "who is this".
//
// Email is a HINT, used for exactly one thing: the strictly-gated
// verified-both-sides link in UserResolver. Treating it as the identity is the
// classic account-takeover bug, and it does not require a malicious IdP — an
// employee leaves, their address is reassigned to a new hire, and the new hire
// logs into the old one's account. Two of the three implementations this package
// replaced had that bug.
// ─────────────────────────────────────────────────────────────────────────────
type Identity struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`

	Email string `json:"email"`

	// EmailVerified is the IdP's assertion, OR the provider-level
	// TrustEmailVerified override. It gates auto-linking, so an unverified email
	// can never attach an identity to an existing account.
	EmailVerified bool `json:"email_verified"`

	Name    *string `json:"name,omitempty"`
	Picture *string `json:"picture,omitempty"`

	// RawClaims is the full claim set, for an application that wants to store or
	// map something this struct does not model.
	//
	// ⚠️ It is UNVALIDATED beyond the signature check on the id_token that carried
	// it. Do not read an authorization decision out of it without deciding, for
	// that specific claim, whether the IdP is authoritative for it.
	RawClaims json.RawMessage `json:"raw_claims,omitempty"`
}

// TokenSet is the raw IdP token material from a login.
//
// An application mints its OWN session and does not need these to authenticate
// anybody. They are worth keeping for exactly one reason: the checkpoint
// introspects them to notice that the upstream grant has been revoked.
//
// ⚠️ THESE ARE LIVE CREDENTIALS. Store them encrypted, or do not store them.
// SessionStore is defined so that encryption is the application's choice and this
// package never has to hold a key — see its documentation.
type TokenSet struct {
	AccessToken  string
	RefreshToken string

	// IDToken is retained for back-channel logout (which needs a `sid`) and for
	// debugging. It is not required to establish the identity — that already
	// happened during Exchange.
	IDToken string
}

// Adapter turns one provider's OAuth2/OIDC dance into an Identity.
//
// Two implementations exist and there should not be a third: a provider that
// needs bespoke Go code is a provider whose quirks belong behind one of these
// two, or a sign that it is not actually OAuth2.
type Adapter interface {
	// AuthCodeURL builds the authorize URL for a login attempt.
	//
	// All three arguments are mandatory and all three are generated by
	// GenerateState, not by the caller:
	//   state    — anti-CSRF, single-use, validated server-side
	//   nonce    — binds the id_token to this request; verified on return
	//   verifier — the PKCE verifier whose S256 challenge is sent
	//
	// ⚠️ An implementation that accepts `verifier` and does not send a challenge
	// derived from it has implemented nothing. That exact bug shipped in one of
	// the flows this package replaced, and it is why the PKCE round trip is
	// asserted end-to-end in adapter_test.go rather than reviewed.
	AuthCodeURL(state, nonce, verifier string) (string, error)

	// Exchange completes the callback: redeems the code (sending the PKCE
	// verifier), verifies what can be verified — including the nonce — and returns
	// the identity plus the tokens.
	Exchange(ctx context.Context, code, verifier, nonce string) (*Identity, *TokenSet, error)
}

// NewAdapter validates the provider and returns the adapter for its kind.
func NewAdapter(ctx context.Context, p *Provider) (Adapter, error) {
	if err := p.Validate(); err != nil {
		return nil, err
	}
	switch p.Kind {
	case KindOIDC:
		return newOIDCAdapter(ctx, p)
	case KindOAuth2:
		return newOAuth2Adapter(p)
	default:
		// Unreachable: Validate rejects unknown kinds. Kept so adding a Kind
		// without an adapter fails loudly instead of returning a nil interface.
		return nil, fmt.Errorf("sso: no adapter for kind %q", p.Kind)
	}
}
